// words.js

const WORD_PACKS = {
    english: {
        easy: [
            "Apple", "Music", "River", "Mountain", "Ocean", "Star", "Sun", "Moon",
            "Book", "Key", "Tree", "Flower", "Bridge", "Road", "Car", "Train",
            "Boat", "Plane", "Bird", "Cat", "Dog", "Fish", "Lion", "Tiger",
            "Bear", "Horse", "Cow", "Pig", "Sheep", "Goat", "Duck", "Frog",
            "Snake", "Spider", "Ant", "Bee", "Fly", "Baby", "Child", "Man",
            "Woman", "Doctor", "Police", "Fire", "Water", "Earth", "Air",
            "Love", "Hate", "War", "Peace", "Life", "Death", "Time", "Space",
            "Art", "Color", "Red", "Green", "Blue", "Yellow", "Black", "White",
            "Food", "Bread", "Cheese", "Milk", "Egg", "Meat", "Fruit", "Pizza",
            "Heart", "Mind", "Soul", "Body", "Hand", "Foot", "Eye", "Ear",
            "Nose", "Mouth", "Tooth", "Hair", "Blood", "Bone", "Skin", "Gold",
            "Silver", "Iron", "Steel", "Wood", "Glass", "Paper", "Stone", "Rock",
            "Sand", "Clay", "Cloth", "Silk", "Wool", "Cotton", "Money", "Coin",
            "King", "Queen", "Prince", "Princess", "Castle", "Sword", "Shield",
            "School", "Teacher", "Student", "Desk", "Chair", "Door", "Window", "Wall",
            "Floor", "Roof", "Room", "Home", "House", "City", "Town", "Village",
            "Farm", "Field", "Forest", "Desert", "Island", "Beach", "Wave", "Sky",
            "Cloud", "Rain", "Snow", "Wind", "Storm", "Light", "Dark",
            "Day", "Night", "Morning", "Evening", "Week", "Month", "Year", "Date",
            "Clock", "Watch", "Phone", "Computer", "TV", "Radio", "Photo", "Paint",
            "Song", "Dance", "Movie", "Game", "Sport", "Ball", "Goal", "Team",
            "Win", "Loss", "Play", "Work", "Sleep", "Dream", "Talk", "Sing",
            "Read", "Write", "Draw", "Run", "Walk", "Jump", "Swim", "Fly",
            "Smile", "Laugh", "Cry", "Sad", "Happy", "Angry", "Fear", "Joy"
        ],
        medium: [
            "Telescope", "Pyramid", "Compass", "Volcano", "Cactus", "Igloo", "Anchor",
            "Magnet", "Robot", "Skeleton", "Tornado", "Rainbow", "Galaxy", "Puzzle",
            "Fossil", "Diamond", "Helmet", "Trophy", "Violin", "Planet", "Jungle",
            "Circus", "Pirate", "Detective", "Vampire", "Ghost", "Alien", "Astronaut",
            "Ninja", "Wizard", "Dragon", "Unicorn", "Mermaid", "Monster", "Zombie",
            "Sphinx", "Mummy", "Genie", "Fairy", "Witch", "Shadow", "Echo", "Mirror",
            "Bubble", "Balloon", "Fireworks", "Dynamite", "Lightning", "Thunder",
            "Hurricane", "Earthquake", "Tsunami", "Avalanche", "Blizzard", "Glacier",
            "Canyon", "Crater", "Oasis", "Swamp", "Lagoon", "Reef", "Cave", "Tunnel",
            "Lighthouse", "Windmill", "Skyscraper", "Stadium", "Museum", "Library",
            "Factory", "Airport", "Station", "Harbor", "Cinema", "Theater", "Aquarium",
            "Zoo", "Garden", "Laboratory", "Pharmacy", "Bakery", "Market", "Restaurant",
            "Hotel", "Ambulance", "Helicopter", "Rocket", "Submarine", "Tractor",
            "Truck", "Motorcycle", "Bicycle", "Skateboard", "Parachute", "Umbrella",
            "Camera", "Microscope", "Compass", "Calculator", "Battery", "Engine"
        ],
        hard: [
            "Algorithm", "Paradigm", "Synergy", "Leverage", "Cryptocurrency", "Blockchain", "Metadata", "Infrastructure",
            "Optimization", "Scalability", "Bandwidth", "Protocol", "Architecture", "Framework", "Middleware", "Interface",
            "Ecosystem", "Analytics", "Stakeholder", "Methodology", "Derivative", "Portfolio", "Volatility", "Equity",
            "Benchmark", "Virtualization", "Encryption", "Authentication", "Authorization", "Firewall", "Malware", "Phishing",
            "Compliance", "Governance", "Arbitration", "Litigation", "Jurisdiction", "Amendment", "Statute", "Precedent",
            "Hypothesis", "Theorem", "Axiom", "Quantum", "Entropy", "Catalyst", "Isotope", "Molecule",
            "Chromosome", "Genome", "Enzyme", "Metabolism", "Mitochondria", "Photosynthesis", "Biodiversity",
            "Democracy", "Bureaucratie", "Diplomacy", "Sovereignty", "Ideology", "Propaganda", "Referendum", "Coalition",
            "Renaissance", "Enlightenment", "Revolution", "Imperialism", "Feudalism", "Colonialism", "Capitalism", "Socialism",
            "Philosophy", "Metaphysics", "Epistemology", "Ethics", "Aesthetics", "Logic", "Dialectic", "Empiricism",
            "Psychology", "Cognition", "Perception", "Consciousness", "Motivation", "Intelligence", "Personality", "Behavior",
            "Sociology", "Anthropology", "Ethnography", "Culture", "Institution", "Stratification", "Urbanization", "Globalization",
            "Economy", "Inflation", "Recession", "Deficit", "Monopoly", "Oligopoly", "Supply", "Demand",
            "Marketing", "Branding", "Segmentation", "Demographics", "Consumer", "Revenue", "Profit", "Margin",
            "Entrepreneurship", "Innovation", "Disruption", "Startup", "Venture", "Investment", "Acquisition", "Merger",
            "Engineering", "Thermodynamics", "Mechanics", "Fluid", "Electromagnetic", "Semiconductor", "Circuit", "Resistance",
            "Medicine", "Diagnosis", "Prognosis", "Symptom", "Syndrome", "Pathology", "Anatomy", "Physiology",
            "Pharmacology", "Antibiotic", "Vaccine", "Immunity", "Inflammation", "Chronic", "Acute", "Therapy",
            "Literature", "Narrative", "Protagonist", "Antagonist", "Metaphor", "Symbolism", "Allegory", "Irony",
            "Linguistics", "Phonetics", "Syntax", "Semantics", "Morphology", "Pragmatics", "Discourse", "Dialect",
            "Mathematics", "Calculus", "Algebra", "Geometry", "Trigonometry", "Statistics", "Probability", "Variable",
            "Physics", "Relativity", "Gravity", "Momentum", "Energy", "Matter", "Particle", "Wave"
        ]
    },
    dutch: {
        easy: [
            "Appel", "Muziek", "Rivier", "Berg", "Oceaan", "Ster", "Zon", "Maan",
            "Boek", "Sleutel", "Boom", "Bloem", "Brug", "Weg", "Auto", "Trein",
            "Boot", "Vliegtuig", "Vogel", "Kat", "Hond", "Vis", "Leeuw", "Tijger",
            "Beer", "Paard", "Koe", "Varken", "Schaap", "Geit", "Eend", "Kikker",
            "Slang", "Spin", "Mier", "Bij", "Vlieg", "Baby", "Kind", "Man",
            "Vrouw", "Dokter", "Politie", "Vuur", "Water", "Aarde", "Lucht",
            "Liefde", "Haat", "Oorlog", "Vrede", "Leven", "Dood", "Tijd", "Ruimte",
            "Kunst", "Kleur", "Rood", "Groen", "Blauw", "Geel", "Zwart", "Wit",
            "Eten", "Brood", "Kaas", "Melk", "Ei", "Vlees", "Fruit", "Pizza",
            "Hart", "Geest", "Ziel", "Lichaam", "Hand", "Voet", "Oog", "Oor",
            "Neus", "Mond", "Tand", "Haar", "Bloed", "Bot", "Huid", "Goud",
            "Zilver", "IJzer", "Staal", "Hout", "Glas", "Papier", "Steen", "Rots",
            "Zand", "Klei", "Doek", "Zijde", "Wol", "Katoen", "Geld", "Munt",
            "Koning", "Koningin", "Prins", "Prinses", "Kasteel", "Zwaard", "Schild",
            "School", "Leraar", "Student", "Bureau", "Stoel", "Deur", "Raam", "Muur",
            "Vloer", "Dak", "Kamer", "Thuis", "Huis", "Stad", "Dorp", "Gehucht",
            "Boerderij", "Veld", "Bos", "Woestijn", "Eiland", "Strand", "Golf",
            "Wolk", "Regen", "Sneeuw", "Wind", "Storm", "Licht", "Donker",
            "Dag", "Nacht", "Ochtend", "Avond", "Week", "Maand", "Jaar", "Datum",
            "Klok", "Horloge", "Telefoon", "Computer", "TV", "Radio", "Foto", "Verf",
            "Lied", "Dans", "Film", "Spel", "Sport", "Bal", "Doel", "Team",
            "Winst", "Verlies", "Spelen", "Werk", "Slapen", "Droom", "Praten", "Zingen",
            "Lezen", "Schrijven", "Tekenen", "Rennen", "Lopen", "Springen", "Zwemmen", "Vliegen",
            "Glimlach", "Lachen", "Huilen", "Verdriet", "Blij", "Boos", "Angst", "Vreugde",
            "Fiets", "Bakker", "Winkel", "Markt", "Haven", "Kerk", "Museum", "Park",
            "Bibliotheek", "Ziekenhuis", "Restaurant", "Café", "Hotel", "Station", "Luchthaven", "Taxi",
            "Bus", "Metro", "Tram", "Snelweg", "Rotonde", "Stoplicht", "Zebrapad", "Parkeerplaats",
            "Benzine", "Garage", "Werkplaats", "Fabriek", "Kantoor", "Vergadering", "Printer",
            "Toetsenbord", "Muis", "Monitor", "Laptop", "Tablet", "Smartphone", "Internet", "Website",
            "Email", "Bericht", "Video", "Podcast", "Nieuws", "Krant",
            "Tijdschrift", "Roman", "Gedicht", "Verhaal", "Brief", "Kaart", "Cadeau",
            "Verjaardag", "Feest", "Bruiloft", "Vakantie", "Weekend", "Uitstapje", "Reis", "Koffer",
            "Paspoort", "Ticket", "Reservering", "Camping", "Tent", "Rugzak", "Wandeling", "Natuur",
            "Dier", "Insect", "Vlinder", "Libel", "Kever", "Wesp", "Hommel", "Rups",
            "Plant", "Struik", "Gras", "Blad", "Tak", "Wortel", "Zaad",
            "Groente", "Ui", "Aardappel", "Tomaat", "Komkommer", "Sla", "Peper",
            "Knoflook", "Peterselie", "Basilicum", "Oregano", "Rozemarijn", "Tijm", "Zout", "Suiker",
            "Meel", "Boter", "Olie", "Azijn", "Mosterd", "Ketchup", "Mayonaise", "Saus",
            "Soep", "Salade", "Sandwich", "Pasta", "Rijst", "Kip",
            "Rundvlees", "Varkensvlees", "Zalm", "Tonijn", "Garnaal", "Mosselen", "Oesters",
            "Ijs", "Chocola", "Koekje", "Taart", "Gebak", "Snoep", "Banaan", "Sinaasappel", 
            "Citroen", "Aardbei", "Framboos", "Blauwe", "Druif", "Meloen"
        ],
        medium: [
            "Telescoop", "Piramide", "Kompas", "Vulkaan", "Cactus", "Iglo", "Anker",
            "Magneet", "Robot", "Skelet", "Tornado", "Regenboog", "Melkweg", "Puzzel",
            "Fossiel", "Diamant", "Helm", "Trofee", "Viool", "Planeet", "Oerwoud",
            "Circus", "Piraat", "Detective", "Vampier", "Spook", "Alien", "Astronaut",
            "Ninja", "Tovenaar", "Draak", "Eenhoorn", "Zeemeermin", "Monster", "Zombie",
            "Sfinx", "Mummie", "Geest", "Fee", "Heks", "Schaduw", "Echo", "Spiegel",
            "Zeepbel", "Ballon", "Vuurwerk", "Dynamiet", "Bliksem", "Donder",
            "Orkaan", "Aardbeving", "Tsunami", "Lawine", "Sneeuwstorm", "Gletsjer",
            "Kloof", "Krater", "Oase", "Moeras", "Lagune", "Rif", "Grot", "Tunnel",
            "Vuurtoren", "Windmolen", "Wolkenkrabber", "Stadion", "Museum", "Bibliotheek",
            "Fabriek", "Luchthaven", "Station", "Haven", "Bioscoop", "Theater", "Aquarium",
            "Dierentuin", "Tuin", "Laboratorium", "Apotheek", "Bakkerij", "Markt", "Restaurant",
            "Hotel", "Ambulance", "Helikopter", "Raket", "Duikboot", "Tractor",
            "Vrachtwagen", "Motorfiets", "Fiets", "Skateboard", "Parachute", "Paraplu",
            "Camera", "Microscoop", "Rekenmachine", "Batterij", "Motor"
        ],
        hard: [
            "Algoritme", "Paradigma", "Synergie", "Hefboom", "Cryptocurrency", "Blockchain", "Metadata", "Infrastructuur",
            "Optimalisatie", "Schaalbaarheid", "Bandbreedte", "Protocol", "Architectuur", "Framework", "Middleware", "Interface",
            "Ecosysteem", "Analytics", "Belanghebbende", "Methodologie", "Derivaat", "Portfolio", "Volatiliteit", "Aandelen",
            "Benchmark", "Virtualisatie", "Encryptie", "Authenticatie", "Autorisatie", "Firewall", "Malware", "Phishing",
            "Naleving", "Governance", "Arbitrage", "Rechtszaak", "Jurisdictie", "Amendement", "Statuut", "Precedent",
            "Hypothese", "Stelling", "Axioma", "Quantum", "Entropie", "Katalysator", "Isotoop", "Molecuul",
            "Chromosoom", "Genoom", "Enzym", "Metabolisme", "Mitochondriën", "Fotosynthese", "Biodiversiteit",
            "Democratie", "Bureaucratie", "Diplomatie", "Soevereiniteit", "Ideologie", "Propaganda", "Referendum", "Coalitie",
            "Renaissance", "Verlichting", "Revolutie", "Imperialisme", "Feodalisme", "Kolonialisme", "Kapitalisme", "Socialisme",
            "Filosofie", "Metafysica", "Epistemologie", "Ethiek", "Esthetica", "Logica", "Dialectiek", "Empirisme",
            "Psychologie", "Cognitie", "Perceptie", "Bewustzijn", "Motivatie", "Intelligentie", "Persoonlijkheid", "Gedrag",
            "Sociologie", "Antropologie", "Etnografie", "Cultuur", "Instituut", "Stratificatie", "Verstedelijking", "Globalisering",
            "Economie", "Inflatie", "Recessie", "Tekort", "Monopolie", "Oligopolie", "Aanbod", "Vraag",
            "Marketing", "Branding", "Segmentatie", "Demografie", "Consument", "Omzet", "Winst", "Marge",
            "Ondernemerschap", "Innovatie", "Disruptie", "Startup", "Onderneming", "Investering", "Overname", "Fusie",
            "Engineering", "Thermodynamica", "Mechanica", "Vloeistof", "Elektromagnetisch", "Halfgeleider", "Circuit", "Weerstand",
            "Geneeskunde", "Diagnose", "Prognose", "Symptoom", "Syndroom", "Pathologie", "Anatomie", "Fysiologie",
            "Farmacologie", "Antibioticum", "Vaccin", "Immuniteit", "Ontsteking", "Chronisch", "Acuut", "Therapie",
            "Literatuur", "Verhaal", "Protagonist", "Antagonist", "Metafoor", "Symboliek", "Allegorie", "Ironie",
            "Taalkunde", "Fonetiek", "Syntaxis", "Semantiek", "Morfologie", "Pragmatiek", "Discours", "Dialect",
            "Wiskunde", "Calculus", "Algebra", "Geometrie", "Goniometrie", "Statistiek", "Waarschijnlijkheid", "Variabele",
            "Fysica", "Relativiteit", "Zwaartekracht", "Momentum", "Energie", "Materie", "Deeltje", "Golf"
        ]
    }
};